os: Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - git submodule update --init --recursive

platform: x64
environment:
  matrix:
    - TARGET_ARCH: x64
    - TARGET_ARCH: ia32

install:
  - ps: Install-Product node 8
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - cmd: SET PATH=C:\python27;%PATH%
  - cmd: node build.js %TARGET_ARCH%
